
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/imooc-bilibili?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: '000415' # Redis服务器连接密码（默认为空）
  servlet:
    multipart:
      max-file-size: 50MB     #单个文件最大限制
      max-request-size: 200MB  #多个文件最大限制

rocketmq:
  name:
    server:
      address: 127.0.0.1:9876

#fastdfs
fdfs:
  tracker-list: 127.0.0.1:22122
  http:
    storage-addr: http://localhost:8088/group1/

server:
  port: 1108



